### ISSUE TITLE
Print hostname when app is deployed

### ISSUE THREAD

**Issue by renehernandez** [renehernandez/appfile#10]
If the app specification declares any domains:

```yaml
# app.yaml
domains:
- domain: example.com
   ...
```
then the execution of `appfile sync -f /path/to/appfile` should output a log message showing the URL where the app will be accessible.

This is specially useful when the domains are dynamically generated based on the environment used by `appfile`
