### ISSUE TITLE
Add capabilities to pull app spec from remote url

### ISSUE THREAD

**Issue by renehernandez** [renehernandez/appfile#43]
This would be a great extension to the current `appfile` capabilities. It would be nice if it could behave similar to what `helm` does with repos and pulling charts from remote.

## Stable repo

Ideally, there would be a stable repo, that could host community-maintained app specifications. In addition, the implementation could support (at least having this in mind for the first iteration) adding custom repos, so that orgs could have their own private repos.

**Note:** Appfile would ship with the stable repo by default

## Implementation

The `appfile` specification would need to be modified to support the new `releases` block instead of the old `specs` block

### appfile spec overview

```yaml
environments:
  review:
    - ..
  production:
    - ..

releases:
  - name: my-ghost # could be optional
    spec: stable/ghost
    values:
      - values.yaml
  ...
```

### Repo commands

```shell
appfile repo add <http_url>
```

```shell
appfile repo list
```

```shell
appfile repo delete
```

```shell
appfile repo update
```

### Limitations

* Spec published in the stable repo need to use a container image with public access. Of course the image field itself could be overwritten to point towards any internal/private container registry
